# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Kril\Documents\kovan\qtpypg\src-taha\layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QMainWindow(object):
    savePoints = False
    points = []
    def setupUi(self, QMainWindow):
        QMainWindow.setObjectName("QMainWindow")
        QMainWindow.resize(1050, 900)
        # Doesn't work for some reason, check later.
        QMainWindow.setWindowIcon(QtGui.QIcon('app_ico.png'))
        self.centralwidget = QtWidgets.QWidget(QMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 800, 800))
        self.graphicsView.setObjectName("graphicsView")
        self.clearDrawingButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearDrawingButton.setGeometry(QtCore.QRect(830, 70, 200, 50))
        self.clearDrawingButton.setObjectName("clearDrawingButton")
        self.toggleConvexDrawingButton = QtWidgets.QPushButton(self.centralwidget)
        self.toggleConvexDrawingButton.setGeometry(QtCore.QRect(830, 10, 200, 50))
        self.toggleConvexDrawingButton.setObjectName("toggleConvexDrawingButton")
        self.toggleConvexDrawingButton.clicked.connect(self.toggleConvexDrawing)
        self.clearLogsButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearLogsButton.setGeometry(QtCore.QRect(830, 760, 200, 50))
        self.clearLogsButton.setObjectName("clearLogsButton")
        self.clearLogsButton.clicked.connect(self.clearLogsPane)
        self.logPane = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.logPane.setGeometry(QtCore.QRect(830, 140, 200, 600))
        self.logPane.setObjectName("plainTextEdit")
        self.logPane.setReadOnly(True)
        QMainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(QMainWindow)
        self.statusbar.setObjectName("statusbar")
        QMainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(QMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1050, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        QMainWindow.setMenuBar(self.menubar)
        self.actionOpen_Preset = QtWidgets.QAction(QMainWindow)
        self.actionOpen_Preset.setObjectName("actionOpen_Preset")
        self.actionSave_Preset = QtWidgets.QAction(QMainWindow)
        self.actionSave_Preset.setObjectName("actionSave_Preset")
        self.actionExit = QtWidgets.QAction(QMainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen_Preset)
        self.menuFile.addAction(self.actionSave_Preset)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.logPane.appendPlainText("Initialized GCS.")
        self.retranslateUi(QMainWindow)
        QtCore.QMetaObject.connectSlotsByName(QMainWindow)

    def retranslateUi(self, QMainWindow):
        # TO-DO: Review this whole translate thing.
        _translate = QtCore.QCoreApplication.translate
        QMainWindow.setWindowTitle(_translate("QMainWindow", "Ground Control Station"))
        self.clearDrawingButton.setText(_translate("QMainWindow", "Clear Drawing"))
        self.toggleConvexDrawingButton.setText(_translate("QMainWindow", "Enable Convex Drawing"))
        self.clearLogsButton.setText(_translate("QMainWindow", "Clear Logs"))
        self.menuFile.setTitle(_translate("QMainWindow", "File"))
        self.menuHelp.setTitle(_translate("QMainWindow", "Help"))
        self.actionOpen_Preset.setText(_translate("QMainWindow", "Open Preset"))
        self.actionSave_Preset.setText(_translate("QMainWindow", "Save Preset"))
        self.actionExit.setText(_translate("QMainWindow", "Exit"))
    
    def toggleConvexDrawing(self):
        if self.savePoints:
            self.logPane.appendPlainText("Stopped recording points.")
            self.toggleConvexDrawingButton.setText("Enable Convex Drawing")
        else:
            self.logPane.appendPlainText("Started recording points.")
            self.toggleConvexDrawingButton.setText("Disable Convex Drawing")
        self.savePoints = not self.savePoints
    
    def clearLogsPane(self):
        self.logPane.clear()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QMainWindow = QtWidgets.QMainWindow()
    ui = Ui_QMainWindow()
    ui.setupUi(QMainWindow)
    QMainWindow.show()
    sys.exit(app.exec_())
